import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  arround: {
    borderRadius: 50,
    borderWidth: 1,
    borderColor: '#fff',
    width: 10,
    height: 10,
    marginRight: 5,
  },
  arroundActive: {
    borderRadius: 50,
    borderWidth: 1,
    borderColor: '#fff',
    width: 10,
    height: 10,
    marginRight: 5,
    backgroundColor: '#fff',
  },
  container: {
    width: '100%',
    backgroundColor: '#000000',
    height: '100%',
    position: 'relative',
  },
  wrap: {
    width: '100%',
    paddingHorizontal: 8,
    // marginBottom: 50,
  },
  notice: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#ffffff',
    textAlign: 'center',
    paddingHorizontal: 12,
  },
  btnAddOpportunities: {
    position: 'absolute',
    zIndex: 9999,
    width: 50,
    height: 50,
    top: '100%',
    right: 10,
    backgroundColor: 'blue',
    borderRadius: 25,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  textAddOpportunities: {
    fontSize: 25,
    color: 'white',
  },
  // opportunities custom styles
  imagePreview: {
    width: '100%',
    height: 200,
  },
  inputTitleWrap: {
    width: '100%',
    backgroundColor: '#202026',
  },
  inputText: {
    borderWidth: 1,
    borderColor: '#3D3B3E',
    backgroundColor: 'transparent',
    width: '100%',
  },
  inputValueText: {
    borderWidth: 1,
    borderColor: '#3D3B3E',
    color: '#91939F',
    backgroundColor: 'transparent',
    width: '100%',
    marginTop: -5,
    height: 26,
  },
  inputValueDescText: {
    borderWidth: 1,
    borderColor: '#3D3B3E',
    color: '#91939F',
    backgroundColor: 'transparent',
    width: '100%',
    height: 150,
    marginTop: -5,
    alignContent: 'flex-start',
    justifyContent: 'flex-start',
    textAlign: 'left',
  },
  inputTitle: {
    backgroundColor: 'transparent',
    color: '#ffffff',
  },
  imageContainer: {
    width: 14,
    height: 14,
    position: 'relative',
  },
  image: {
    top: 2,
    width: '100%',
    height: '100%',
    position: 'relative',
  },
  btnDoneWrap: {
    backgroundColor: '#0E46F1',
    color: '#ffffff',
    borderRadius: 8,
    alignContent: 'center',
    justifyContent: 'center',
    height: 48,
  },
  btnDoneText: {
    fontFamily: 'Raleway',
    fontWeight: '600',
    fontSize: 16,
    color: '#ffffff',
    textAlign: 'center',
    width: '100%',
  },
  containerHorizontalFilters: {
    flexDirection: 'row',
    overflow: 'scroll',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    // height: 70,
    // marginBottom: 20,
  },
  noticeFilter: {
    // padding: 10,
    backgroundColor: 'transparent',
    // borderRadius: 12,
    // height: 40,
    // marginTop: 17,
    // marginBottom: 20,
  },
  btnsContainerBiggest: {
    marginTop: 20,
    flexDirection: 'row',
    justifyContent: 'space-between', // можно и без него
    gap: 5, // или вместо него использовать marginRight
    width: '100%',
    left: 0,
  },
});
