export enum EmotionsEnum {
  ANGER = 'Anger',
  ANXIETY = 'Anxiety',
  CALMNESS = 'Calmness',
  CURIOSITY = 'Curiosity',
  FEAR = 'Fear',
  GRATITUDE = 'Gratitude',
  HAPPINESS = 'Happiness',
  HOPE = 'Hope',
  JOY = 'Joy',
  LOVE = 'Love',
  PLEASURE = 'Pleasure',
  PRIDE = 'Pride',
  SADNESS = 'Sadness',
  SLEAP = 'sleap',
  SHYNESS = 'Shyness',
  SURPRICE = 'surprice',
}
